name: Test Project
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./second-action-react-demo
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print current dir
        run: pwd
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Run tests
        run: npm test
        working-directory: ${{ env.working-directory }}
